export interface IndividualStatsAVG {
  goals: number
  assists: number
  saves: number
  ownGoals: number
  shotsTarget: number
  passes: number
  passesCompletion: string // "0.00%"
  rebounds: number
  duels: number
  interceptions: number
  clearances: number
  bpRatio: string // "0 / 0"
  overallScore: number
  cs: number // Clean Sheet (0 или 1)
}

export interface Player {
  id: number
  player: string
  elo: number
  gamesPlayed: number
  winnedGames: number
  loosedGames: number
  position: 'GK' | 'DM' | 'AM' | 'ST'
  individualStatsAVG: IndividualStatsAVG
}

export const dta = [{ssn1:[],ssn2:[],ssn3:[],ssn4:[],ssn5:[]}]

export const data: Player[] = [
  {
    id: 1,
    player: 'VIRTUAL',
    elo: 2450,
    gamesPlayed: 50,
    winnedGames: 42,
    loosedGames: 8,
    position: 'DM',
    individualStatsAVG: {
      goals: 1,
      assists: 0,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 1,
      passes: 15,
      passesCompletion: '100.00%',
      rebounds: 0,
      duels: 5,
      interceptions: 2,
      clearances: 1,
      bpRatio: '2 / 2',
      overallScore: 93,
      cs: 1,
    },
  },
  {
    id: 2,
    player: 'Slayer_777',
    elo: 2310,
    gamesPlayed: 48,
    winnedGames: 35,
    loosedGames: 13,
    position: 'GK',
    individualStatsAVG: {
      goals: 3,
      assists: 1,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 4,
      passes: 22,
      passesCompletion: '85.50%',
      rebounds: 1,
      duels: 8,
      interceptions: 3,
      clearances: 0,
      bpRatio: '5 / 6',
      overallScore: 89,
      cs: 0,
    },
  },
  {
    id: 3,
    player: 'Mistik',
    elo: 2180,
    gamesPlayed: 52,
    winnedGames: 30,
    loosedGames: 22,
    position: 'GK',
    individualStatsAVG: {
      goals: 0,
      assists: 4,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 1,
      passes: 45,
      passesCompletion: '92.00%',
      rebounds: 2,
      duels: 12,
      interceptions: 5,
      clearances: 3,
      bpRatio: '8 / 10',
      overallScore: 85,
      cs: 1,
    },
  },
  {
    id: 4,
    player: 'Turbo_Oleg',
    elo: 1950,
    gamesPlayed: 40,
    winnedGames: 25,
    loosedGames: 15,
    position: 'ST',
    individualStatsAVG: {
      goals: 2,
      assists: 0,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 2,
      passes: 10,
      passesCompletion: '70.00%',
      rebounds: 0,
      duels: 4,
      interceptions: 1,
      clearances: 0,
      bpRatio: '1 / 3',
      overallScore: 78,
      cs: 0,
    },
  },
  {
    id: 5,
    player: 'IronWall',
    elo: 1890,
    gamesPlayed: 45,
    winnedGames: 20,
    loosedGames: 25,
    position: 'DM',
    individualStatsAVG: {
      goals: 0,
      assists: 0,
      saves: 12,
      ownGoals: 0,
      shotsTarget: 0,
      passes: 30,
      passesCompletion: '60.00%',
      rebounds: 5,
      duels: 2,
      interceptions: 0,
      clearances: 10,
      bpRatio: '0 / 0',
      overallScore: 82,
      cs: 1,
    },
  },
  {
    id: 6,
    player: 'Flash_Boy',
    elo: 1720,
    gamesPlayed: 38,
    winnedGames: 18,
    loosedGames: 20,
    position: 'ST',
    individualStatsAVG: {
      goals: 1,
      assists: 2,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 3,
      passes: 28,
      passesCompletion: '78.00%',
      rebounds: 1,
      duels: 6,
      interceptions: 2,
      clearances: 1,
      bpRatio: '4 / 4',
      overallScore: 75,
      cs: 0,
    },
  },
  {
    id: 7,
    player: 'ShadowKiller',
    elo: 1650,
    gamesPlayed: 55,
    winnedGames: 22,
    loosedGames: 33,
    position: 'AM',
    individualStatsAVG: {
      goals: 0,
      assists: 1,
      saves: 0,
      ownGoals: 1,
      shotsTarget: 0,
      passes: 18,
      passesCompletion: '65.00%',
      rebounds: 0,
      duels: 9,
      interceptions: 4,
      clearances: 5,
      bpRatio: '2 / 5',
      overallScore: 68,
      cs: 0,
    },
  },
  {
    id: 8,
    player: 'NoobMaster69',
    elo: 1400,
    gamesPlayed: 30,
    winnedGames: 10,
    loosedGames: 20,
    position: 'AM',
    individualStatsAVG: {
      goals: 0,
      assists: 0,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 1,
      passes: 12,
      passesCompletion: '50.00%',
      rebounds: 0,
      duels: 3,
      interceptions: 1,
      clearances: 0,
      bpRatio: '0 / 2',
      overallScore: 55,
      cs: 0,
    },
  },
  {
    id: 9,
    player: 'GoalMachine',
    elo: 1320,
    gamesPlayed: 25,
    winnedGames: 12,
    loosedGames: 13,
    position: 'DM',
    individualStatsAVG: {
      goals: 5,
      assists: 0,
      saves: 0,
      ownGoals: 0,
      shotsTarget: 6,
      passes: 5,
      passesCompletion: '40.00%',
      rebounds: 1,
      duels: 2,
      interceptions: 0,
      clearances: 0,
      bpRatio: '1 / 1',
      overallScore: 88,
      cs: 0,
    },
  },
  {
    id: 10,
    player: 'UnluckyGuy',
    elo: 1100,
    gamesPlayed: 60,
    winnedGames: 5,
    loosedGames: 55,
    position: 'DM',
    individualStatsAVG: {
      goals: 0,
      assists: 0,
      saves: 0,
      ownGoals: 3,
      shotsTarget: 0,
      passes: 50,
      passesCompletion: '30.00%',
      rebounds: 2,
      duels: 1,
      interceptions: 1,
      clearances: 2,
      bpRatio: '1 / 10',
      overallScore: 42,
      cs: 0,
    },
  },
]
